### ISSUE TITLE
Omezení studenta k odzápisu

### ISSUE THREAD

**Issue by Bumross** [KopyTKG/laborky#29]
Při přihlášení uživatele "student"
Na stránce /student/moje
je zobrazení všech termínů, na kterých byl/je student zapsán.

Otázka:
Kdy se nejpozději může student odzapsat od termínu?
Řeší toto omezení FE nebo BE?

**Comment by KopyTKG** [comment]
Hele limit je brán podle stagu což je 24h. A řešení by mělo být FE i BE  protože FE můžeš lehce obejít (FE už řeší basic check na Date.NOW < time.start a podle toho blokuje tlačítko)

**Comment by Bumross** [comment]
Dobře, dám tam podmínku. Chceš v respondu i "moznost_odepsat": bool ?

**Comment by KopyTKG** [comment]
Hele neni třeba jen při tom co vám přijde request tak checkni čas a podle toho  dej 200  a nebo 409
