### ISSUE TITLE
Zobrazení dostupných termínů pro studenta

### ISSUE THREAD

**Issue by Bumross** [KopyTKG/laborky#30]
Při přihlášení uživatele "student"
na straně /student

je zobrazení veškerých termínů dostupné pro studenta.
Nyní se filtruje:
- pouze ty termíny, které se váží na předmět, které má student zapsán na portálu STAG
- pouze ty termíny, které ještě neproběhly (jejich termin.datum > curr.date)
- pouze ty termíny, které "identifikační číslo" ještě student nesplnil (např: Lab 1, Lab 2, Lab 3 z PCA)

Mají se studentovi zobrazovat termíny i do minulosti (ty, které již proběhly)?

Můj návrh: studentovi se budou zobrazovat i termíny 1 hodinu do minulosti po startu termínu (v případě, že by student došel na termín, který by byl "volný" na poslední moment)

**Comment by Midiros** [comment]
Zmena na d16855e1d3dfbbce8e212d3d563cc7108589d218
Naimplementovano, aktualne je teda moznost se zapsat na jiz "probihajici" termin max. 1 hodinu zpet (Lze zmenit)
