### ISSUE TITLE
API route /profil špatný formát

### ISSUE THREAD

**Issue by KopyTKG** [KopyTKG/laborky#38]
routa `/profil` má podle zadaní vracet datum splnění místo čísla 1

```json
{
  "KPPPO2R": [
    0,
    0
  ],
  "KIPCA": [
    0,
    0,
    0
  ],
  "CS102": [],
  "KMPMPS1": [
    1,
    1,
    0,
    0
  ],
  "CS101": [
    0,
    0
  ],
  "MATH202": [
    0,
    0,
    0
  ]
}
```
stačí jen datum

**Comment by Bumross** [comment]
Issue opraven

Potřebuji otestovat:
Pokud má student splněná všechna cvičení, zda se zobrazí u učitele "hodnej žák"
