### ISSUE TITLE
Filtr na zobrazení předmětů 

### ISSUE THREAD

**Issue by Bumross** [KopyTKG/laborky#44]
Každá role bude mít filtrování termínů podle předmětů

- update místo zkratky předmětu vracím celé KAT/PRED

Role:
admin:
- možnost na výběr mezi všemi předměty

ucitel:
- možnost na výběr mezi předměty, kterými je on cvičící (TODO)

student:
- možnost na výběr mezi předměty, které studuje a nemá uznané všechna cvičení (TODO)

**Comment by DanielRiha8906** [comment]
Done.
