### ISSUE TITLE
Funkce na vyhledávání studenta pomocí Fčísla

### ISSUE THREAD

**Issue by Bumross** [KopyTKG/laborky#45]
Potřebujeme "asi" endpoint, který nám vrátí studenta, kterého učitel vyhledá pomocí Fčísla.
vstup: id studenta (Fčíslo), kod_predmetu

Logika:
pokud student nebude v databázi, vrátí to "Neregistrovaný uživatel"

pokud ho to najde, vrátí mu to informace:
jaká cvičení má student splněné (student/profil {kod_predmetu}) , na jakých termínech je student zapsán (student/moje {kod_predmetu} ), jaké termíny má student k dispozici (i obsazené) (/student {kod_predmetu} )

tohle je slepovací úloha již existujících funkcí, potřebujeme jen vytvořit možnost pro učitele, aby si studenta zobrazil, případně mu nějaký termín uznal, aby mu uznal celý předmět a nebo aby ho zapsal na termín

**Comment by KopyTKG** [comment]
same as #49
