### ISSUE TITLE
Posílání notifikace (skrz email) studentům - STAG

### ISSUE THREAD

**Issue by Bumross** [KopyTKG/laborky#47]
Musíme zjistit, jak se dá poslat email přes přihlášeného učitele všem studentům, kteří mají předmět k dispozici a měli by o termín zájem.

Prohledat prostě Stag WS a zjistit možnosti, jak se toto dá řešit.

**Comment by DanielRiha8906** [comment]
Projel jsem všechny endpointy na restu u stag dema. žádný tam není.
Tudíž tady bych asi přemýšlel o exportování CSVčka, nebo jednoduchého texťáku, který dostane učitel a dá to do emailu jako adresu příjemců.

**Comment by KopyTKG** [comment]
Rework ---> issue #75
