### ISSUE TITLE
Vypsání termínu vázáno na vyučujícího

### ISSUE THREAD

**Issue by Bumross** [KopyTKG/laborky#50]
Vyučující může vypsat termín pouze na předmět, kterého je vyučující

- bude používat funkci, která najde všechny předměty vyučujícího
- vyučující bude mít na výběr pouze z jeho vyučovaných předmětů, aby předmět vypsal

**Comment by Midiros** [comment]
1823e4142c67b86f49170e75017954aa909c85e6
Prvni cast vypracovana, get_predmet_by_vyucujici vraci vsechny kody predmetu, ktere vyucujici vyucuje.

**Comment by Bumross** [comment]
Zatím nebudeme aplikovat, toto musíme vyřešit až v po produkci, kdy budeme mít reálná data na vyzkoušení.
Nemáme dostatečnou databázi a vyučující, abychom to mohli aplikovat nyní.

Ponecháme v tomto stavu
