### ISSUE TITLE
Filrtovaní update

### ISSUE THREAD

**Issue by KopyTKG** [KopyTKG/laborky#70]
Když jsem dneska dodělával filtrování tak jsem si uvědomil že by nebylo špatné tam přidat možnost ignorovat již proběhlé termíny

**Comment by Bumross** [comment]
API bude přijímat ještě bool parametr "ignorovat_probehle", defaultně bude False?

**Comment by KopyTKG** [comment]
> API bude přijímat ještě bool parametr "ignorovat_probehle", defaultně bude False?

Hele ještě je třeba se o tom pobavit jak to budeme řešit
