### ISSUE TITLE
Učitel = možnost zapsat studenta na termín

### ISSUE THREAD

**Issue by KopyTKG** [KopyTKG/laborky#71]
Koukám na API a nenašel jsem možnost zapsat studenta na termín. Tak se chci zeptat zda li je tu možnost to přidat či to dělat nebudem?

**Comment by Bumross** [comment]
Byl pouze špatný název v API
Nyní se nachází na endpoint: /ucitel/splnit
vstupní informace: ticket, id_stud, id_terminu
