### ISSUE TITLE
Notifikace při výpisu či změně termínu

### ISSUE THREAD

**Issue by KopyTKG** [KopyTKG/laborky#75]
Takže po prohledávání stackoverflow tak jsem zjistil že je možnost přes FE otevřít email s skupinou mailů předmětem a i celým tělem mailu a pak je jen na učitelovy či jej chce poslat. Tudíž je tu potřeba aby když je zvolena notifikace při vytváření či změně tak aby routa mi vracela  maily a když ne tak jen "ok"

**Comment by Bumross** [comment]
Chceš, aby ti to sestrojilo rovnou message toho mailu, kterou bychom z BE dávali rovnou tobě?
Nechám chata, aby něco napsal, ale určitě bude obsahovat:

Předmět, číslo cvičení, název termínu, a datum konání

**Comment by KopyTKG** [comment]
hele momentalne je problem ze nejsem schopen data body do emailu ale jinak je potreba poslat jen maily

**Comment by KopyTKG** [comment]
Update: => demo-stag zase funguje a je tu možnost brát data jako jsou emaily podle předmětu a další @Bumross

**Comment by Bumross** [comment]
opraveno
Api ROUTE /ucitel/termin přidání a úprava - může vracet mimo "ok" i list emailů studentů (když bude parametr upozornit = True) , kteří by mohli mít o termín zájem.
