### ISSUE TITLE
Přehled úspěšných studentů

### ISSUE THREAD

**Issue by KopyTKG** [KopyTKG/laborky#79]
problematika pro FE i BE, kdy budu potřebovat asi API route s vstupem `ticket` (klasika) a asi `kod_predmet` pro vyhledávání

vrace bych potom chtěl json v tomto stylu
```json
{
 "kod_predmetu": "test/test", 
 "studenti": [
  {
   "osCislo": "test",
   "email": "test@test.test",
   "jmeno": "test",
   "prijmeni": "test"
  },
],
}
```

lze potom upravit podle dat

**Comment by Bumross** [comment]
Backendová část hotová - vracíme v požadovaném json stylu
API ROUTE: /ucitel/uspesni_studenti
parametry: ticket, kod_predmetu
