### ISSUE TITLE
Automatické přidání všech studentů studujících předmět

### ISSUE THREAD

**Issue by KopyTKG** [KopyTKG/laborky#80]
Takže problém je tento. Při prvním přihlášení za učitele nejsou žádní studenti v DB. Tudíž nejde uznat předmět ani splnit cvičení a to samé nejde zapsat student na termín. Protože neni v DB. Další problém je při vytváření nelze upozornit studenty protože se to hledá přes DB.

Tak navrhuji při vytvoření termínu automaticky přidat všechny studenty co nejsou v DB a tím lze obejít nedostatek studentů pro problematiku co je nahoře

@Midiros @DanielRiha8906  @Bumross

**Comment by Bumross** [comment]
dobrý návrh
automatické vytváření studentů se bude dít:
- když se vytvoří předmět, přidat do db všechny studenty, kteří mají předmět zapsaný
- když učitel vyhledá osCislo, které není v DB, vytvoří se jeho profil (pokud předmět studuje)
