### ISSUE TITLE
Upozornění studenta na termín

### ISSUE THREAD

**Issue by Bumross** [KopyTKG/laborky#82]
Problém:
když je student zapsán na termínu, tak dostane i tak upozornění o vypsání termínu stejného čísla - i když ž je zapsán někde jinde

nutno přidat novou query na upozornění
nutná kontrola, jak funguje upozornění na nově vypsaný termín a na upravený termín

**Comment by DanielRiha8906** [comment]
Otestováno. Fixnuto.
